# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pool:
  name: default
stages:
- stage: Build 
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    variables:
      imageRegistry: docker.io
      imageProject: zhangchl007
      myApp: spring-azure-demo
      tag: '$(Build.BuildId)'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: BuildpacksInstaller@1
      inputs:
        buildpacksVersion: '0.26.0'
    - task: BuildpacksTask@1
      displayName: Buildpack Container Images
      inputs:
        command: 'build'
        imageName: '$(imageRegistry)/$(imageProject)/$(myApp):$(tag)'
        builder: 'paketobuildpacks/builder:base'
        projectPath: 'target/spring-azure-demo-0.0.1-SNAPSHOT.jar'
        pullPolicy: 'if-not-present'
    - task: Docker@2
      displayName: Push Container Image
      inputs:
        containerRegistry: 'mydockerhub'
        repository: '$(imageProject)/$(myApp)'
        command: 'push'
    - upload: deploy/manifests
      artifact: deploy/manifests
- stage: Deploy
  displayName: Deploy stage
  variables:
    k8sImage: '$(imageRegistry)/$(imageProject)/$(myApp):$(tag)'
    imagePullSecret: 'mydockersecret'
    tag: '$(Build.BuildId)'
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'spring-azure-demo'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'mydemo_aks'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(imagePullSecret)'
              dockerRegistryEndpoint: 'mydockerhub'
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'mydemo_aks'
              namespace: 'default'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: deploy/springazuredemo
              chartName: 'springazuredemo'
              chartVersion: '0.1.0'
              releaseName: 'springazuredemo'
              overrideValues: 'image.tag=$(tag)'
